const express=require('express')
const router=express.Router()
const user_handler=require('../router_handler/user')
router.get('/student',user_handler.student)
router.get('/login',user_handler.login)
router.get('/personalinfo',user_handler.personalinfo)
router.get('/personalscore',user_handler.personalscore)
router.get('/Schedule',user_handler.Schedule)
router.post('/Newpassword',user_handler.Newpassword)
router.post('/NewTpassword',user_handler.NewTpassword)
router.get('/TeacherInfo',user_handler.TeacherInfo)
router.get('/TeachCourse',user_handler.TeachCourse)
router.get('/AverageScore',user_handler.AverageScore)
router.get('/MyStudentScore',user_handler.MyStudentScore)
router.post('/pushStudentScore',user_handler.pushStudentScore)
router.post('/NewMpassword',user_handler.NewMpassword)
router.post('/TeacherIncrease',user_handler.TeacherIncrease)
router.post('/TeacherChange',user_handler.TeacherChange)
router.post('/FindTeacher',user_handler.FindTeacher)
router.post('/deleteTeacher',user_handler.deleteTeacher)
router.post('/MTeacherPassword',user_handler.MTeacherPassword)
router.post('/StudentIncrease',user_handler.StudentIncrease)
router.post('/StudentChange',user_handler.StudentChange)
router.post('/FindStudent',user_handler.FindStudent)
router.post('/deleteStudent',user_handler.deleteStudent)
router.post('/MStudentPassword',user_handler.MStudentPassword)
router.post('/CourseIncrease',user_handler.CourseIncrease)
router.post('/CourseChange',user_handler.CourseChange)
router.post('/FindCourse',user_handler.FindCourse)
router.post('/deleteCourse',user_handler.deleteCourse)
module.exports=router